/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./src/**/*.{html,js}"],
  theme: {
    screens: {
      sm: { max: "700px" },
    },
    colors: {
      light: {
        primary: "#E92577",
        white: "#FFFFFF",
        black: "#000000",
        textlightgray: "#777777",
        textdarkgray: "#0A0A14",
        textdarkpink: "#AF0C48",
        headerlightpink: "#EA2678",
        ornamentblue: "#82BBFF",
        ornamentgray: "#D9D9D9",
        bggray: "#F4F4F4",
        cerulean: "#1769FF",
        ornamentdarkgray: "#525252",
        pastelblue: "#DDEEFE",
        pastelgreen: "#D9F6F1",
        blue: "#0077B5",
        redpink: "#B92B5F",
        reduxpurple: "#764ABC",
        amber: "#FFE86E",
        turquoise: "#038FD6",
      },
      dark: {
        primary: "#E92577",
        white: "#FFFFFF",
        black: "#000000",
        textlightgray: "#777777",
        textdarkgray: "#0A0A14",
        textdarkpink: "#AF0C48",
        headerlightpink: "#EA2678",
        ornamentblue: "#82BBFF",
        ornamentgray: "#D9D9D9",
        bggray1: "#2A262B",
        bggray2: "#484148",
        cerulean: "#1769FF",
        ornamentdarkgray: "#525252",
        pastelblue: "#DDEEFE",
        pastelgreen: "#D9F6F1",
        blue: "#0077B5",
        redpink: "#B92B5F",
        reduxpurple: "#764ABC",
        amber: "#FFE86E",
        turquoise: "#419CCB",
      },
    },
    extend: {},
  },
  plugins: [],
};
